export const hidden1: string;
export const show1: string;
export const hidden2: string;
export const show2: string;
export const hidden3: string;
export const show3: string;
export const hidden4: string;
export const show4: string;
export const std: string;
